server {
    listen 81;
    listen [::]:81;
    server_name 139.196.115.78;

    root /srv/server-service-navigator;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
}
